# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [3]:
lst=np.array([1,2,3,4,5])
lst

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [4]:
mat=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [6]:
built_inMat=np.arange(1,18,2).reshape(3,3)
built_inMat

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [14]:
l=np.random.randn(10)
l

array([-0.67752926,  0.44819918,  1.15975271, -1.15848603, -0.94786343,
       -1.44401546,  1.24687948,  1.8069473 , -0.00458178,  0.79246572])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [19]:
num2DArray=np.arange(1,6).reshape(5,1)
num2DArray

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [20]:
num2DArray.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [33]:
myarray=np.array([2,4,6,8,10,12,14,16,18,20])
print(myarray)
print("3rd element: {}".format(myarray[2]))
print("4th element: {}".format(myarray[3]))
print("9th element: {}".format(myarray[8]))

[ 2  4  6  8 10 12 14 16 18 20]
3rd element: 6
4th element: 8
9th element: 18


Print alternate elements of that array

In [34]:
myarray[0::2]

array([ 2,  6, 10, 14, 18])

Change last 3 elements into 100 using broadcasting and print

In [39]:
myarray[7:]=100
myarray

array([  2,   4,   6,   8,  10,  12,  14, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [57]:
mymatrix=np.random.rand(25).reshape(5,5)
mymatrix

array([[0.0342278 , 0.8176811 , 0.20746243, 0.27117999, 0.54722716],
       [0.78471899, 0.35677976, 0.26260298, 0.02453151, 0.15540234],
       [0.75906039, 0.9163455 , 0.49624815, 0.85762506, 0.70354496],
       [0.23186914, 0.01347546, 0.39974199, 0.02854789, 0.76943062],
       [0.45178828, 0.08769175, 0.13667995, 0.77336329, 0.76618532]])

In [83]:
mymatrix[1:4, 1:4] 

array([[0.35677976, 0.26260298, 0.02453151],
       [0.9163455 , 0.49624815, 0.85762506],
       [0.01347546, 0.39974199, 0.02854789]])